version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/gax-kotlin
    steps:
      - checkout
      - restore_cache:
          keys:
          - gax-kotlin-dependencies-{{ checksum "build.gradle" }}
      - run: 
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gax-kotlin-dependencies-{{ checksum "build.gradle" }}        
      - run: 
           name: Build and run checks
           command: ./gradlew check
      - run: 
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit        
      - run: 
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
          when: always

  build_examples:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run checks
          command: ./gradlew check
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - build_examples
